name: CI

on: 
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_tool:
    name: Test_Upgrade
    runs-on: macos-latest

    strategy:
      matrix:
       include:
         - os: windows-latest
         - os: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.100'

    - name: Build - CI
      shell: pwsh
      run: |
        dotnet workload install --from-rollback-file 8.0.100.json android ios maccatalyst maui tvos

    - name: Build - CI
      shell: pwsh
      run: |
        dotnet workload list

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.101'

    - name: Build - CI
      shell: pwsh
      run: |
        dotnet workload install --from-rollback-file 8.0.101.json android ios maccatalyst maui tvos

    - name: Build - CI
      shell: pwsh
      run: |
        dotnet workload list
